version: '3.2'

services:

  redis:
    image: redis:latest
    container_name: convey-redis-dev
    ports:
      - '6379:6379'
    environment:
      REDIS_MASTER_HOST: master
      REDIS_MASTER_PORT_NUMBER: 6379